# ============================================================
# PIPELINE CI/CD - Proyecto Flask (ProjectoAPIREST)
# ============================================================

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectFolder: 'ProjectoAPIREST'    # 👈 nombre exacto de tu carpeta
  artifactName: 'build_artifact'

steps:
# ============================================================
# 1️⃣ Verificar estructura de archivos
# ============================================================
- script: |
    echo "📁 Directorio actual:"
    pwd
    echo "📂 Contenido del repositorio:"
    ls -la
  displayName: 'Verificar contenido raíz del repo'

# ============================================================
# 2️⃣ Usar Python 3.10
# ============================================================
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Usar Python 3.10'

# ============================================================
# 3️⃣ Instalar dependencias del sistema
# ============================================================
- script: |
    sudo apt-get update -y
    sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
  displayName: 'Instalar dependencias del sistema'

# ============================================================
# 4️⃣ Instalar dependencias Python del proyecto Flask
# ============================================================
- script: |
    echo "📦 Entrando en carpeta del proyecto: $(projectFolder)"
    cd $(projectFolder)
    echo "📂 Archivos dentro de la carpeta:"
    ls -la
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt
  displayName: 'Instalar dependencias Python'

# ============================================================
# 5️⃣ Levantar la app Flask (modo prueba con SQLite)
# ============================================================
- script: |
    cd $(projectFolder)
    echo "🚀 Iniciando API Flask..."
    export DATABASE_URL="sqlite:///test.db"
    python -u app.py > ../app_stdout.log 2> ../app_stderr.log &
    echo $! > ../app.pid
    sleep 5
    echo "✅ Flask levantado."
  displayName: 'Levantar Flask'

# ============================================================
# 6️⃣ Ejecutar pruebas automáticas
# ============================================================
- script: |
    cd $(projectFolder)
    echo "🧪 Ejecutando pruebas automáticas..."
    python Test_api.py
  displayName: 'Ejecutar Test_api.py'

# ============================================================
# 7️⃣ Detener Flask
# ============================================================
- script: |
    if [ -f app.pid ]; then
      echo "🛑 Deteniendo Flask..."
      kill $(cat app.pid)
      rm -f app.pid
    else
      echo "⚠ No se encontró app.pid"
    fi
  displayName: 'Detener aplicación Flask'

# ============================================================
# 8️⃣ Empaquetar aplicación en ZIP
# ============================================================
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/$(projectFolder)'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifactName).zip'
    replaceExistingArchive: true
  displayName: 'Empaquetar proyecto en ZIP'

# ============================================================
# 9️⃣ Publicar artifact
# ============================================================
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publicar artifact'