# ============================================================
# PIPELINE CI/CD - Proyecto Flask (ProjectoAPIREST)
# ============================================================

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectFolder: 'ProjectoAPIREST'    # 👈 nombre exacto de tu carpeta
  artifactName: 'build_artifact'

steps:
# ============================================================
# 1️⃣ Verificar estructura del repositorio
# ============================================================
- script: |
    echo "📁 Directorio actual:"
    pwd
    echo "📂 Contenido del repositorio:"
    ls -la
  displayName: 'Verificar contenido raíz del repo'

# ============================================================
# 2️⃣ Configurar Python 3.10
# ============================================================
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Usar Python 3.10'

# ============================================================
# 3️⃣ Instalar dependencias del sistema
# ============================================================
- script: |
    sudo apt-get update -y
    sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
  displayName: 'Instalar dependencias del sistema'

# ============================================================
# 4️⃣ Instalar dependencias del proyecto Flask
# ============================================================
- script: |
    echo "📦 Entrando en carpeta del proyecto: $(projectFolder)"
    cd $(projectFolder)
    echo "📂 Archivos dentro de la carpeta:"
    ls -la
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt
  displayName: 'Instalar dependencias Python'

# ============================================================
# 5️⃣ Levantar API Flask con SQLite (en background)
# ============================================================
- script: |
    cd $(projectFolder)
    echo "🚀 Iniciando API Flask (modo prueba con SQLite)..."
    export DATABASE_URL="sqlite:///test.db"
    python -u app.py > ../app_stdout.log 2> ../app_stderr.log &
    echo $! > ../app.pid
    echo "⏳ Esperando 10 segundos para que la API se inicialice..."
    sleep 10
    echo "🔎 Verificando si el puerto 5000 está activo..."
    ss -lntp | grep :5000 || echo "⚠ El puerto 5000 no parece estar escuchando todavía."
  displayName: 'Levantar Flask en background con espera'

# ============================================================
# 6️⃣ Ejecutar pruebas automáticas de la API
# ============================================================
- script: |
    cd $(projectFolder)
    echo "🧪 Ejecutando pruebas automáticas (Test_api.py)..."
    python Test_api.py || echo "⚠ Algunas pruebas fallaron."
    echo "📄 Logs de Flask (stdout):"
    cat ../app_stdout.log || true
    echo "📄 Logs de Flask (stderr):"
    cat ../app_stderr.log || true
  displayName: 'Ejecutar Test_api.py con logs'

# ============================================================
# 7️⃣ Detener la aplicación Flask
# ============================================================
- script: |
    if [ -f app.pid ]; then
      echo "🛑 Deteniendo Flask..."
      kill $(cat app.pid)
      rm -f app.pid
    else
      echo "⚠ No se encontró app.pid"
    fi
  displayName: 'Detener aplicación Flask'

# ============================================================
# 8️⃣ Empaquetar el proyecto en ZIP
# ============================================================
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/$(projectFolder)'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifactName).zip'
    replaceExistingArchive: true
  displayName: 'Empaquetar proyecto en ZIP'

# ============================================================
# 9️⃣ Publicar artifact ZIP
# ============================================================
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publicar artifact'