# ============================================================
# PIPELINE CI - Proyecto Flask (Sistema de Películas)
# ============================================================

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: 'build_artifact'

steps:
# ============================================================
# 1️⃣ Verificar directorio actual y contenido
# ============================================================
- script: |
    echo "📁 Directorio actual:"
    pwd
    echo "📂 Archivos y carpetas disponibles:"
    ls -la
  displayName: 'Verificar contenido del directorio'

# ============================================================
# 2️⃣ Usar Python 3.10
# ============================================================
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Usar Python 3.10'

# ============================================================
# 3️⃣ Instalar dependencias del sistema
# ============================================================
- script: |
    sudo apt-get update -y
    sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
  displayName: 'Instalar dependencias del sistema'

# ============================================================
# 4️⃣ Instalar dependencias Python (Flask)
# ============================================================
- script: |
    echo "📦 Instalando dependencias del proyecto Flask..."
    python -m pip install --upgrade pip setuptools wheel
    # ==========================================
    # 🔧 IMPORTANTE: CAMBIA ESTA RUTA SI TU ARCHIVO ESTÁ EN UNA CARPETA
    # Si tu requirements.txt está en la raíz -> deja como está
    # Si está dentro de 'peliculas/' cámbialo a: pip install -r peliculas/requirements.txt
    # ==========================================
    if [ -f requirements.txt ]; then
        pip install -r requirements.txt
    elif [ -f peliculas/requirements.txt ]; then
        pip install -r peliculas/requirements.txt
    elif [ -f backend/requirements.txt ]; then
        pip install -r backend/requirements.txt
    else
        echo "⚠ No se encontró requirements.txt en las rutas conocidas."
        exit 1
    fi
  displayName: 'Instalar dependencias Python'

# ============================================================
# 5️⃣ Levantar la app Flask en background usando SQLite
# ============================================================
- script: |
    echo "🚀 Iniciando API Flask con base de datos SQLite..."
    export DATABASE_URL="sqlite:///test.db"
    python -u app.py > app_stdout.log 2> app_stderr.log &
    echo $! > app.pid
    sleep 5
    echo "✅ Flask debería estar corriendo ahora."
  displayName: 'Levantar Flask (modo prueba)'

# ============================================================
# 6️⃣ Ejecutar pruebas automáticas
# ============================================================
- script: |
    echo "🧪 Ejecutando pruebas de API (Test_api.py)..."
    python Test_api.py || echo "⚠ Algunos tests fallaron."
  displayName: 'Ejecutar Test_api.py'

# ============================================================
# 7️⃣ Detener Flask
# ============================================================
- script: |
    if [ -f app.pid ]; then
      echo "🛑 Deteniendo Flask..."
      kill $(cat app.pid)
      rm -f app.pid
    else
      echo "⚠ No se encontró app.pid"
    fi
  displayName: 'Detener aplicación Flask'

# ============================================================
# 8️⃣ Empaquetar proyecto en ZIP
# ============================================================
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifactName).zip'
    replaceExistingArchive: true
  displayName: 'Empaquetar proyecto en ZIP'

# ============================================================
# 9️⃣ Publicar artifact (ZIP)
# ============================================================
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publicar artifact'